export const DEFAULT_TEMPO = 120
export const MIN_TEMPO = DEFAULT_TEMPO / 2
export const MAX_TEMPO = (DEFAULT_TEMPO * 2) - MIN_TEMPO
export const STEP_TEMPO = DEFAULT_TEMPO / 8

export const REACT_APP_CONTENTFUL_SPACE = process.env.REACT_APP_CONTENTFUL_SPACE
export const REACT_APP_CONTENTFUL_ACCESS_TOKEN = process.env.REACT_APP_CONTENTFUL_ACCESS_TOKEN

export const SPACE_KEY_CODE = 32
